"""
PlacementGNN — Topology-Only GNN for Initial Placement Prediction

Predicts per-macro heatmap over a G×G grid from netlist topology alone.
Used for ML initial placement → CP-SAT legalize → ALNS refine pipeline.

Output: (V, G²) logits, decoded to positions via Gumbel-softmax sampling.
K proposals generated by K independent Gumbel samples from same logits.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from typing import Optional

from gnn_layers import ReluMLP, LinearMessagePassingLayer


class PlacementGNN(nn.Module):
    """
    Topology-only GNN producing per-macro heatmap over G×G grid.

    Architecture:
        - Node encoder: 4D features → hidden_dim
        - Edge encoder: 4D pin offsets → hidden_dim
        - Message passing: n_layers of LinearMessagePassingLayer (mean aggregation)
        - Heatmap head: hidden_dim → G² logits per macro

    Node features (position-independent, 14D by default):
        [size_w, size_h, degree_norm, area_frac,
         lap_pe_0..7,  (Laplacian positional encodings)
         eigvec_centrality, clustering_coeff]

    Why topology-only: we're predicting positions, so there's no spatial graph
    to build (chicken-and-egg). Netlist topology carries all the information
    about which macros should be placed near each other.

    Why Laplacian PE: gives the GNN global topology awareness — which macros
    are in the same graph partition, how far apart they are structurally.
    Critical for generalization across different circuits.

    Why mean_aggr: normalizes for variable-degree nodes, preventing high-degree
    macros from dominating message passing.
    """

    def __init__(
        self,
        node_input_dim: int = 14,
        topo_edge_dim: int = 4,
        hidden_dim: int = 64,
        n_layers: int = 5,
        grid_size: int = 16,
        mean_aggr: bool = True,
    ):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        self.grid_size = grid_size

        # Node encoder
        self.node_encoder = ReluMLP([node_input_dim, hidden_dim, hidden_dim])

        # Edge encoder (pin offsets)
        self.topo_edge_encoder = ReluMLP([topo_edge_dim, hidden_dim, hidden_dim])

        # Message passing layers
        self.topo_layers = nn.ModuleList([
            LinearMessagePassingLayer(
                node_dim=hidden_dim,
                edge_dim=hidden_dim,
                message_dim=hidden_dim,
                mean_aggr=mean_aggr,
            )
            for _ in range(n_layers)
        ])

        # Heatmap head: predicts per-macro distribution over G² cells
        g2 = grid_size * grid_size
        self.heatmap_head = nn.Sequential(
            ReluMLP([hidden_dim, hidden_dim]),
            nn.Linear(hidden_dim, g2),
        )
        nn.init.xavier_normal_(self.heatmap_head[-1].weight, gain=0.1)
        nn.init.zeros_(self.heatmap_head[-1].bias)

    def forward(
        self,
        node_features: torch.Tensor,
        edge_index: torch.Tensor,
        edge_attr: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            node_features: (V, node_input_dim) macro features
            edge_index: (2, E) netlist edges
            edge_attr: (E, topo_edge_dim) pin offsets

        Returns:
            logits: (V, G²) raw heatmap logits per macro
        """
        h = self.node_encoder(node_features)
        edge_enc = self.topo_edge_encoder(edge_attr)

        for layer in self.topo_layers:
            h = layer(h, edge_index, edge_enc)

        return self.heatmap_head(h)  # (V, G²)


def compute_laplacian_pe(edge_index: torch.Tensor, V: int, k: int = 8) -> torch.Tensor:
    """Compute k smallest non-trivial eigenvectors of the graph Laplacian.

    Uses the normalized Laplacian L = I - D^{-1/2} A D^{-1/2}.
    Deterministic sign convention: each eigenvector is flipped so that
    the entry with largest absolute value is positive.

    Args:
        edge_index: (2, E) undirected edges
        V: number of nodes
        k: number of eigenvectors to return

    Returns:
        pe: (V, k) Laplacian positional encodings
    """
    device = edge_index.device

    # Build adjacency and degree on CPU (numpy eigh is faster for small V)
    src = edge_index[0].cpu().numpy()
    dst = edge_index[1].cpu().numpy()
    A = np.zeros((V, V), dtype=np.float32)
    np.add.at(A, (src, dst), 1.0)
    # Symmetrize (should already be bidirectional, but be safe)
    A = np.maximum(A, A.T)
    # Remove self-loops
    np.fill_diagonal(A, 0.0)

    deg = A.sum(axis=1)
    deg_inv_sqrt = np.zeros(V, dtype=np.float32)
    mask = deg > 0
    deg_inv_sqrt[mask] = 1.0 / np.sqrt(deg[mask])

    # Normalized Laplacian: L = I - D^{-1/2} A D^{-1/2}
    D_inv_sqrt = np.diag(deg_inv_sqrt)
    L = np.eye(V, dtype=np.float32) - D_inv_sqrt @ A @ D_inv_sqrt

    # Eigen decomposition
    try:
        eigenvalues, eigenvectors = np.linalg.eigh(L)
    except np.linalg.LinAlgError:
        return torch.zeros(V, k, device=device)

    # Skip first eigenvector (constant, eigenvalue ≈ 0), take next k
    k_actual = min(k, V - 1)
    pe = eigenvectors[:, 1:1 + k_actual]  # (V, k_actual)

    # Pad if V-1 < k
    if k_actual < k:
        pe = np.pad(pe, ((0, 0), (0, k - k_actual)), mode='constant')

    # Deterministic sign flip: sign convention based on largest-magnitude entry
    # (standard approach: flip so that the entry with largest absolute value is positive)
    for j in range(pe.shape[1]):
        max_idx = np.argmax(np.abs(pe[:, j]))
        if pe[max_idx, j] < 0:
            pe[:, j] = -pe[:, j]

    return torch.from_numpy(pe).to(device)


def compute_centrality_features(edge_index: torch.Tensor, V: int) -> torch.Tensor:
    """Compute centrality features: eigenvector centrality + clustering coefficient.

    Args:
        edge_index: (2, E) undirected edges
        V: number of nodes

    Returns:
        features: (V, 2) [eigenvec_centrality_norm, clustering_coeff]
    """
    device = edge_index.device
    src = edge_index[0].cpu().numpy()
    dst = edge_index[1].cpu().numpy()

    # Build adjacency
    A = np.zeros((V, V), dtype=np.float32)
    np.add.at(A, (src, dst), 1.0)
    A = np.maximum(A, A.T)
    np.fill_diagonal(A, 0.0)

    # Eigenvector centrality: leading eigenvector of A
    try:
        eigenvalues, eigenvectors = np.linalg.eigh(A)
        ev_centrality = np.abs(eigenvectors[:, -1])  # largest eigenvalue
        ev_max = ev_centrality.max()
        if ev_max > 0:
            ev_centrality /= ev_max
    except np.linalg.LinAlgError:
        ev_centrality = np.zeros(V, dtype=np.float32)

    # Clustering coefficient
    deg = A.sum(axis=1)
    A_bool = (A > 0).astype(np.float32)
    # triangles[i] = (A^3)[i,i] / 2  but for undirected: A²·A diagonal
    A2 = A_bool @ A_bool
    triangles = np.array([A2[i] @ A_bool[i] for i in range(V)]) / 2.0
    max_triangles = deg * (deg - 1) / 2.0
    clustering = np.zeros(V, dtype=np.float32)
    valid = max_triangles > 0
    clustering[valid] = triangles[valid] / max_triangles[valid]

    features = np.stack([ev_centrality, clustering], axis=1)  # (V, 2)
    return torch.from_numpy(features).to(device)


def build_node_features(
    sizes: torch.Tensor,
    edge_index: torch.Tensor,
    V: int,
    lap_pe_dim: int = 8,
) -> torch.Tensor:
    """
    Build position-independent node features with global graph structure.

    Features (4 + lap_pe_dim + 2 = 14 by default):
        [size_w, size_h, degree_norm, area_frac,
         lap_pe_0, ..., lap_pe_{k-1},
         eigvec_centrality, clustering_coeff]

    Args:
        sizes: (V, 2) macro widths and heights (normalized to canvas)
        edge_index: (2, E) netlist edges
        V: number of macros
        lap_pe_dim: number of Laplacian PE dimensions (default 8)

    Returns:
        features: (V, 4 + lap_pe_dim + 2) node features
    """
    device = sizes.device

    # Degree: count edges per node
    degree = torch.zeros(V, device=device)
    src = edge_index[0]
    degree.scatter_add_(0, src, torch.ones(src.shape[0], device=device))
    # Normalize
    max_deg = degree.max().clamp(min=1.0)
    degree_norm = degree / max_deg

    # Area fraction
    areas = sizes[:, 0] * sizes[:, 1]
    total_area = areas.sum().clamp(min=1e-8)
    area_frac = areas / total_area

    # Laplacian PE (global topology awareness)
    lap_pe = compute_laplacian_pe(edge_index, V, k=lap_pe_dim)  # (V, lap_pe_dim)

    # Centrality features
    centrality = compute_centrality_features(edge_index, V)  # (V, 2)

    base = torch.stack([
        sizes[:, 0],
        sizes[:, 1],
        degree_norm,
        area_frac,
    ], dim=1)  # (V, 4)

    return torch.cat([base, lap_pe, centrality], dim=1)  # (V, 4 + lap_pe_dim + 2)


def decode_heatmap_hard(
    logits: torch.Tensor,
    grid_centers: torch.Tensor,
    tau: float = 0.1,
) -> torch.Tensor:
    """
    Sample cell assignments via Gumbel-softmax (hard) → positions at cell centers.

    Args:
        logits: (V, G²) raw logits
        grid_centers: (G², 2) cell center coordinates
        tau: Gumbel temperature

    Returns:
        positions: (V, 2)
    """
    weights = F.gumbel_softmax(logits, tau=tau, hard=True)  # (V, G²)
    return weights @ grid_centers  # (V, 2)


def decode_heatmap_soft(
    logits: torch.Tensor,
    grid_centers: torch.Tensor,
    tau: float = 1.0,
) -> torch.Tensor:
    """
    Gumbel-softmax soft relaxation for differentiable training loss.

    Args:
        logits: (V, G²) raw logits
        grid_centers: (G², 2) cell center coordinates
        tau: Gumbel temperature (higher = softer)

    Returns:
        positions: (V, 2) soft positions
    """
    weights = F.gumbel_softmax(logits, tau=tau, hard=False)  # (V, G²)
    return weights @ grid_centers  # (V, 2)


def decode_heatmap_argmax(
    logits: torch.Tensor,
    grid_centers: torch.Tensor,
) -> torch.Tensor:
    """
    Deterministic decode: argmax cell per macro.

    Args:
        logits: (V, G²) raw logits
        grid_centers: (G², 2) cell center coordinates

    Returns:
        positions: (V, 2)
    """
    cell_ids = logits.argmax(dim=1)  # (V,)
    return grid_centers[cell_ids]  # (V, 2)


def decode_heatmap_jitter(
    logits: torch.Tensor,
    grid_centers: torch.Tensor,
    grid_size: int,
    seed: int = 0,
) -> torch.Tensor:
    """
    Argmax cell + random offset within cell to reduce collisions.

    Multiple macros at the same cell get different jitter, breaking
    exact-overlap that makes legalization destructive.

    Args:
        logits: (V, G²) raw logits
        grid_centers: (G², 2) cell center coordinates
        grid_size: G for G×G grid
        seed: random seed for jitter

    Returns:
        positions: (V, 2)
    """
    cell_ids = logits.argmax(dim=1)  # (V,)
    pos = grid_centers[cell_ids].clone()  # (V, 2)
    cell_size = 2.0 / grid_size
    gen = torch.Generator().manual_seed(seed)
    offset = (torch.rand(pos.shape, generator=gen) - 0.5) * cell_size * 0.67
    pos = (pos + offset.to(pos.device)).clamp(-1.0, 1.0)
    return pos


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------

def _toy_test():
    """Quick sanity check: forward/backward pass, correct shapes."""
    print("PlacementGNN toy test")
    print("=" * 50)

    V, E = 20, 40
    G = 16
    device = 'cpu'

    # Random data
    sizes = torch.rand(V, 2, device=device) * 0.3 + 0.05
    edge_index = torch.randint(0, V, (2, E), device=device)
    edge_attr = torch.randn(E, 4, device=device)

    # Build features (now 14D with Laplacian PE + centrality)
    features = build_node_features(sizes, edge_index, V)
    assert features.shape == (V, 14), f"features shape {features.shape}"
    print(f"  Node features: {features.shape}")

    # Model (node_input_dim=14 by default now)
    model = PlacementGNN(grid_size=G)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"  Parameters: {n_params:,}")

    # Forward
    logits = model(features, edge_index, edge_attr)
    assert logits.shape == (V, G * G), f"logits shape {logits.shape}"
    print(f"  Logits shape: {logits.shape}")

    # Backward
    logits.sum().backward()
    print(f"  Backward: OK")

    # Decode
    from differentiable_hpwl import build_grid_centers
    grid_centers = build_grid_centers(G)

    pos_hard = decode_heatmap_hard(logits.detach(), grid_centers)
    assert pos_hard.shape == (V, 2), f"hard decode shape {pos_hard.shape}"
    assert pos_hard.min() >= -1.0 and pos_hard.max() <= 1.0
    print(f"  Hard decode: {pos_hard.shape}, range [{pos_hard.min():.3f}, {pos_hard.max():.3f}]")

    pos_soft = decode_heatmap_soft(logits, grid_centers, tau=1.0)
    assert pos_soft.shape == (V, 2)
    print(f"  Soft decode: {pos_soft.shape}, range [{pos_soft.min():.3f}, {pos_soft.max():.3f}]")

    pos_argmax = decode_heatmap_argmax(logits.detach(), grid_centers)
    assert pos_argmax.shape == (V, 2)
    print(f"  Argmax decode: {pos_argmax.shape}")

    # Gradient flow through soft decode
    model.zero_grad()
    logits2 = model(features, edge_index, edge_attr)
    pos_soft2 = decode_heatmap_soft(logits2, grid_centers, tau=0.5)
    loss = pos_soft2.sum()
    loss.backward()
    has_grad = any(p.grad is not None and p.grad.abs().sum() > 0
                   for p in model.parameters())
    assert has_grad, "Gradient must flow through soft decode"
    print(f"  Gradient through soft decode: OK")

    print("\nAll tests passed!")


if __name__ == '__main__':
    _toy_test()
